import collections

input_ = """
prtkqyluibmtcwqaezjmhgfndx
prtkqylusbsmcwvaezjmhgfndt
prgkqyluibsocwvamzjmhgkndx
prjkqyluibsocwvahzjmhgfnsx
prtkqylcibsocwvzezjohgfndx
prtkqyluiksocwziezjmhgfndx
prikqyluiksocwvaezjmkgfndx
prtkgyluibsocwvwezjehgfndx
prtkqyluiysocwvaezjghxfndx
prtkqwluibsoxwvaezjmhgfhdx
prtkqylgibsocwvabzjmhzfndx
prtknyltibnocwvaezjmhgfndx
prdkqyluibrocwvaezjmhgnndx
prtwqyluibsoctvcezjmhgfndx
mrtkqyluibgocwvakzjmhgfndx
prtkqaouibsocwvaezjmhwfndx
prtkqyluihjocwvaezjmhgfpdx
prtkqyluikfxcwvaezjmhgfndx
prtkqybuixsocwvaczjmhgfndx
pvtkayluibsocwxaezjmhgfndx
grtkqgluibsocdvaezjmhgfndx
prlkqyluibsochvaezjmhgzndx
prtkqylxibsocmvaezjmhgfkdx
prtkqyluibsqctvaezjmpgfndx
putkqyluibsocqvaezjmhgfndw
prtjqyluibsiclvaezjmhgfndx
prtkqylvpvsocwvaezjmhgfndx
prnkqyluibsocwvaezjmhefsdx
prtktyluibsocwvaezjkhgrndx
prtkqyluibcovwvaezjthgfndx
prtkqcluibiocwvaezjmhggndx
prtkqyluihsocwveezjmhgfydx
prtklyluibsocwqaszjmhgfndx
prtkqyluibsocwvaezjmfznndx
prtkjyluijsocwvaeejmhgfndx
prtkqtluibsonwvaexjmhgfndx
prtkqyluinsocwbaezjmjgfndx
prtkqyluibslckvaezjmhgyndx
prtkqyluibsodwlpezjmhgfndx
prtkquluibsfcwvaezjhhgfndx
prtkqyluhbsocweaezsmhgfndx
prrkqyluinsocxvaezjmhgfndx
prtkqyluibsoswvaezjmhgyqdx
prtkqbluibdocwvlezjmhgfndx
prtkqyfuibsocpvaezjmhgfnwx
prtkqlluibsqjwvaezjmhgfndx
prtkqyluibrocwvaehjmjgfndx
prtkqyluibsoowvaezgmhgendx
wrtjqyluibsocwvaezfmhgfndx
prtvqyluhbsocwvaezjmtgfndx
prtkqyllibspcwvaezjmkgfndx
pqtzqyeuibsocwvaezjmhgfndx
prtkqyluibsolpvaezjmegfndx
przkayguibsocwvaezjmhgfndx
prtkqyluidsocwvaezjmyufndx
prtuqyluibsocwvaezjmfgfnkx
prtkqwluibsrcwvaezjchgfndx
prtkqyluibsotwhaozjmhgfndx
erwkqylhibsocwvaezjmhgfndx
prtkqyluibsocwvgezjmkgfedx
prskqyluiesocwvaezjmggfndx
prtkqylmitsocwvaezjmhgfnox
prtkqyluinnocwvaezjmhgfkdx
prtktyluibsokwvaezjmhgfcdx
prtkqyluibsomwvakvjmhgfndx
prtkqyltibloawvaezjmhgfndx
prtkqyluibxocwvaezgmhgqndx
prtkqyluibskcmvaezjmhgfngx
artkqylubbsotwvaezjmhgfndx
prtkqyluibzocwvhezjmhgfnbx
prskqkluibsocwvaezjmhgfjdx
prtkqyluibwocwvaezjkhglndx
prukqyluissocwvzezjmhgfndx
puhkqyluibsocwvaezjmhgfsdx
qrtkqyluibsocwvaeujmhgfndd
prtkqyluibsoctvaezjmagfnda
prtkquluibsocwkaezjmhgfqdx
prtkqyluubswcwvaezjmhvfndx
prfkqyluibsocwvaemrmhgfndx
pmtkqyluibpocwvaezjmhggndx
prtkqvluibiocwvaezjqhgfndx
prtkgypuibsocwvaezcmhgfndx
prtpqyquibsovwvaezjmhgfndx
prtwqyluiasocwvaexjmhgfndx
mrtzqyluibbocwvaezjmhgfndx
prtkqyluibsocwmaegwmhgfndx
prtkqyluibvncwvaqzjmhgfndx
prtkqyluiusocwvaezjmhmfbgx
prtkqyljibvocwvaezjehgfndx
prtkqyloibsopavaezjmhgfndx
prckqyakibsocwvaezjmhgfndx
prtkqyluibsdcwvaezjmngfddx
prekqylupbsocwvaezemhgfndx
hrtkqyluibhocwvaezjmhgfnde
prmkqyluibsocwvaezzfhgfndx
prtkqyluiccfcwvaezjmhgfndx
pdtkqyluxbsocwvaezjmhgendx
prokqyluibsocwvuezjmsgfndx
prtkqyluibsacwvaezjyhgfndv
prtkqmluibsocavaezjmhgfndc
prtkqyluibsocwvmezjmhgtnqx
prtkqytuibiocyvaezjmhgfndx
pktkqyiuibsocwvwezjmhgfndx
grtrqyluibsocwvaezjmhgfbdx
prtkqylsibjocwvaezjmhgfnyx
prtkqyhutbsocwvaexjmhgfndx
prtknyluibsocmvaezumhgfndx
prtkwyluibsocwvahzjmhgpndx
prtkqywuibsolhvaezjmhgfndx
prtkcyluibsoccvaezjthgfndx
prtkqyrdibsocwvaezjbhgfndx
prtkqyhuqbsocwvaezjmhgfxdx
pytkqyluibsocwvagzjmhgfndv
prtkqyliibsocwvaexwmhgfndx
prtkqyluibshcwvaeljphgfndx
prtkqyluibsocwvaerjzhbfndx
prtkqyduibsocwvaezvmhgfnzx
drtkqylhibsocwvaezjmhmfndx
prtkqyluibsocwvaezamfvfndx
brtkqyluqbsocwvaezjmhgpndx
prtkqyiuibsocwvuezjmhgfngx
urtkqyluibsocqvaeljmhgfndx
prtkqyluikaocwvaezjmhgfjdx
prqkqzouibsocwvaezjmhgfndx
prtkqyluibsocxvaezjmhgfnxv
prlkqyluibsoxwvaeijmhgfndx
prthuyluibsocwvaezjmhgfnhx
potkqyluizsocwvaezjmhifndx
fstkqyduibsocwvaezjmhgfndx
prtkqxluibsocwvaezjmhgffdm
prtkqylpibsozwvaezmmhgfndx
prxkqylbibsocwvaezjphgfndx
srtkqyluibsicnvaezjmhgfndx
prtktyluibsocwvaezjvhgfnax
pctkqyluxbsocwvaezwmhgfndx
prtkqylusbsoclvaezsmhgfndx
pwtkqyluibsocrvaezjmggfndx
prtkqyluibswcwraezjmhgfndd
prtkqyluibtocwiaezjmhgfnax
prtuqyluibsocwvajzjmngfndx
pwtkqyluibsocwvaerjmogfndx
petkqexuibsocwvaezjmhgfndx
pztkqyluibsocwvaerqmhgfndx
prtkqyluobsocwvaezjmapfndx
prtkqyluiinocwvaeljmhgfndx
prtkqyluibsoowvxezjmhgfnnx
lrtkqyluibsocwvfezjmhgfndc
prtkqyluibokcwvahzjmhgfndx
prtkqmlufbsocwvaegjmhgfndx
prtkqylribsocwvanzjmhgfnda
prtkqyluibspxwvaezkmhgfndx
prtiqyluibsbcwvaezjmhgfntx
prikqzluinsocwvaezjmhgfndx
prtkqnldibsocwvaezjmhxfndx
prtkqyluixsocsvaezjmhwfndx
hrtkqyluibsocwvaezjhhgfodx
prtkqyluibsrcwvaezjmhpfwdx
prtkqyluibsocwyaezjmhgffdk
prtkqyluidsocwvalmjmhgfndx
prukquluabsocwvaezjmhgfndx
prckqyluinsmcwvaezjmhgfndx
prbkqymuibsocwvaezjmhgfndc
prtkfylaibsocwvaezjmkgfndx
zrtkqyluibsocwvrbzjmhgfndx
crtkqyluibsocwvaejjmkgfndx
prttqyluibsocyvaezymhgfndx
prtkqylugbsocwvaezjxhgfmdx
prtkqyluibsocwdlezjmhgfnbx
prtkqjluibsocwvaozjhhgfndx
prtcjyluibsocwbaezjmhgfndx
rrtkqyluiblocwvaezjmhgundx
prtkkyluibsocwfaezjmhgfnyx
prtkqyuuibsocwvaezjmhgfogx
prtkyyluvbsocwvaezjmhgfnox
prpkqyluibyocwvaezjmhggndx
pdtkqyluibdocwvaezjmhgfndy
prtklysuibsocwvaezjmhgfnwx
prtkqyluabsouwvaekjmhgfndx
phtkqyluibsocwvaezjmhgfnxt
prtkqyxuibsocwvaezjmhpfnqx
prtkqyluibsodwsaezdmhgfndx
prtkbyluibsohwvaezjmhgfndr
xrtkqylhibsocwvtezjmhgfndx
prtkqyluvysocwvaezbmhgfndx
prtkqieuibsocwvaeojmhgfndx
pctkqyluibsocwvanzjmhgfnux
vrtkqyluibsozwvaezjmhgandx
prtkqyluiusocwvaezjmhmfngx
prbkqyluibsockvaxzjmhgfndx
prtkqyluibsonwvaczjmhgfndi
prtkqyluiblocwvaezjmhgfnau
prtkqyluibsocwvafzuchgfndx
prdkqyluiysocwvaezjmhgfnax
prnkqyouibsocwvaezjmhgfndq
mrtkqgluibsocwvpezjmhgfndx
pvtkqyluibsocwvaczjmhgnndx
trtkqwluibsohwvaezjmhgfndx
prmkqyluibsofwvaezjmhgfrdx
prtyqyluibpdcwvaezjmhgfndx
ertkqylulbsocwvaezjmhgfnax
prtkqyluibsacwvaeijmhgfndf
prtkqyluibyocwvapzjmhgpndx
potkqyluibgocwvaezjmhzfndx
prtkqyluibsocwyaezxmhgfnpx
prtkqkjuibsncwvaezjmhgfndx
prtqqyluibsocwlaezjmhgkndx
prtkxyluibnocwvaezjmhgkndx
prtkqyluiosocwvapzjmxgfndx
prtkqylumbsocwvyezimhgfndx
prukqyluibsocwvyezjmhgindx
prtkqylbibstcwvaezjxhgfndx
pctkqyuuibsocwvaezjuhgfndx
vrtkqyluibsocwvaezjmhgfnll
urtkqyluibsopwvaezjphgfndx
prtkceluibsocwvaepjmhgfndx
prwkxyluibsocwvaezjmhgfnzx
prtkqyluitsocwvaezqzhgfndx
prtkqkauibsorwvaezjmhgfndx
prtkqyluibsocwvaezfmftfndx
prtkiybuibsocwvaezjkhgfndx
prtkzyluibsocwgaezjmvgfndx
prtkqyluibsocwvaezjmhgqnxg
prtkqyluimsocwvauzjwhgfndx
prtkqyluibsacwgaezjmhgfndd
pwtkuyluibsccwvaezjmhgfndx
prtkqyluibsoawvaezjmvgfnlx
prtkqyluabsocwwaezjmhgftdx
patkqylnibsocwvaezjmhgfnox
prtkqyluibsocwlaxzkmhgfndx
pbtkqpluibsfcwvaezjmhgfndx
prtkqyluibsoywsaezjmhgxndx
prtkqyluibfocwvaezjyhgfhdx
pltbqylcibsocwvaezjmhgfndx
prtkdyluiisocwvvezjmhgfndx
prtkqkxuibsokwvaezjmhgfndx
prtkqyluibsoawvaezzmhgfndm
petkqyluibsgcwvaezjmhgfndu
prtkqyluibsoyxvaezjmlgfndx
prtkqyluibxocwvaezgmhnfndx
prtkikluibsocwvwezjmhgfndx
prbkqyluibsocwvaezjhhgfnux
prtkqylufbsxcwvaezjmhgfnfx
prtkqyluibsdcdvaezjmhgxndx
potkiyluibsocwvaezjmhkfndx
prtkqyluiosocsvhezjmhgfndx
prtkqyluibsocqbaezomhgfndx
prtihyluibsocwvaeujmhgfndx
prtuquruibsocwvaezjmhgfndx
prtkqyloibsocwvaeztmhifndx
ertuqyluibsocwvaeajmhgfndx
""".strip().split('\n')


def part1():
    twos = 0
    threes = 0

    for line in input_:
        counts = collections.Counter(line)

        if any(v == 2 for v in counts.values()):
            twos += 1

        if any(v == 3 for v in counts.values()):
            threes += 1

    return twos * threes


def part2():
    for i, candidate in enumerate(input_):
        for comparison in input_[i+1:]:
            different_letters = []
            same_letters = []

            for candidate_letter, comparison_letter in zip(candidate, comparison):
                if candidate_letter == comparison_letter:
                    same_letters.append(candidate_letter)
                else:
                    different_letters.append((candidate_letter, comparison_letter))

            if len(different_letters) == 1:
                return ''.join(same_letters)


print(part1())
print(part2())
